// This file is autogenerated by liwe3-svelte
/* eslint-disable @typescript-eslint/no-explicit-any */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

/** SystemDomain */
export interface SystemDomain {
	/** the main id field */
	id: string;
	/** The domain unique code */
	code: string;
	/** The domain name */
	name: string;
	/** If the domain is visible */
	visible?: boolean;
}

/** SystemTheme */
export interface SystemTheme {
	/** the main id field */
	id: string;
	/** The domain code */
	domain: string;
	/** The Theme data */
	data?: any;
}

/** SystemDomainAdmin */
export interface SystemDomainAdmin {
	/** the main id field */
	id: string;
	/** The domain unique code */
	code: string;
	/** The domain name */
	name: string;
	/** If the domain is visible */
	visible: boolean;
}

/** SystemDomainPublic */
export interface SystemDomainPublic {
	/** the main id field */
	id: string;
	/**  */
	code: string;
	/**  */
	name: string;
}

